name: sleepwell
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #For timeing 
  ntp: 2.0.0  
  get: ^4.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  #for the  // await Splash until other items loaded in the main 
  flutter_native_splash: ^2.3.10
  # For alarm
  slide_digital_clock: ^1.0.3
  
  #FireBase section:

  firebase_core: ^2.25.5
  get_storage: ^2.1.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  flutter_settings_screens: ^0.3.3-null-safety+2
  #fore login loading 
  modal_progress_hud_nsn: ^0.5.1

  #For Time in Clock
  intl: ^0.19.0
  
  
  
  
  #on boarding page 
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  #math option
  math_expressions: ^2.4.0
  alarm: ^3.0.14
  permission_handler: ^11.3.1
  audioplayers: ^5.2.1
  flutter_spinbox: ^0.13.1
  fl_chart: ^0.68.0
  persistent_bottom_nav_bar: ^5.0.2
  http: ^1.2.1
  # flutter_local_notifications: ^17.1.2

  timezone: ^0.9.3

  connectivity_plus: ^6.0.3
  rxdart: ^0.28.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.1
  google_sign_in: ^6.2.1
  # tflite_flutter: ^0.10.4




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
    - assets/
    - assets/music/
    - assets/logo2.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages