// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA64oHB5DBpkCzsZ9PzdiwIkVceuQ5WvAo',
    appId: '1:705225154575:web:bc9cdd56579b3a5c73c37a',
    messagingSenderId: '705225154575',
    projectId: 'sleepwell-2d0c4',
    authDomain: 'sleepwell-2d0c4.firebaseapp.com',
    storageBucket: 'sleepwell-2d0c4.appspot.com',
    measurementId: 'G-XQTNZWEK4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBun53CttUKoTpq2tmqqrvz5hpLkp2GTMw',
    appId: '1:705225154575:android:9c93a1b6cb1551a573c37a',
    messagingSenderId: '705225154575',
    projectId: 'sleepwell-2d0c4',
    storageBucket: 'sleepwell-2d0c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvQoEYHoLFQd4ZO6fFByV0pC_N84bImbY',
    appId: '1:705225154575:ios:194b82d6fb2b613073c37a',
    messagingSenderId: '705225154575',
    projectId: 'sleepwell-2d0c4',
    storageBucket: 'sleepwell-2d0c4.appspot.com',
    iosBundleId: 'com.example.sleepwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvQoEYHoLFQd4ZO6fFByV0pC_N84bImbY',
    appId: '1:705225154575:ios:5f95c2d82af817dc73c37a',
    messagingSenderId: '705225154575',
    projectId: 'sleepwell-2d0c4',
    storageBucket: 'sleepwell-2d0c4.appspot.com',
    iosBundleId: 'com.example.sleepwell.RunnerTests',
  );
}
